(cl:defpackage pp_msgs-srv
  (:use )
  (:export
   "MOVEITPLUGIN"
   "<MOVEITPLUGIN-REQUEST>"
   "MOVEITPLUGIN-REQUEST"
   "<MOVEITPLUGIN-RESPONSE>"
   "MOVEITPLUGIN-RESPONSE"
   "PATHPLANNINGPLUGIN"
   "<PATHPLANNINGPLUGIN-REQUEST>"
   "PATHPLANNINGPLUGIN-REQUEST"
   "<PATHPLANNINGPLUGIN-RESPONSE>"
   "PATHPLANNINGPLUGIN-RESPONSE"
  ))

