// Generated by gencpp from file pp_msgs/MoveItPlugin.msg
// DO NOT EDIT!


#ifndef PP_MSGS_MESSAGE_MOVEITPLUGIN_H
#define PP_MSGS_MESSAGE_MOVEITPLUGIN_H

#include <ros/service_traits.h>


#include <pp_msgs/MoveItPluginRequest.h>
#include <pp_msgs/MoveItPluginResponse.h>


namespace pp_msgs
{

struct MoveItPlugin
{

typedef MoveItPluginRequest Request;
typedef MoveItPluginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveItPlugin
} // namespace pp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pp_msgs::MoveItPlugin > {
  static const char* value()
  {
    return "7cd51e786e5ea2edaffb4c8c1c95c872";
  }

  static const char* value(const ::pp_msgs::MoveItPlugin&) { return value(); }
};

template<>
struct DataType< ::pp_msgs::MoveItPlugin > {
  static const char* value()
  {
    return "pp_msgs/MoveItPlugin";
  }

  static const char* value(const ::pp_msgs::MoveItPlugin&) { return value(); }
};


// service_traits::MD5Sum< ::pp_msgs::MoveItPluginRequest> should match
// service_traits::MD5Sum< ::pp_msgs::MoveItPlugin >
template<>
struct MD5Sum< ::pp_msgs::MoveItPluginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::MoveItPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MoveItPluginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::MoveItPluginRequest> should match
// service_traits::DataType< ::pp_msgs::MoveItPlugin >
template<>
struct DataType< ::pp_msgs::MoveItPluginRequest>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::MoveItPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MoveItPluginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pp_msgs::MoveItPluginResponse> should match
// service_traits::MD5Sum< ::pp_msgs::MoveItPlugin >
template<>
struct MD5Sum< ::pp_msgs::MoveItPluginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::MoveItPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MoveItPluginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::MoveItPluginResponse> should match
// service_traits::DataType< ::pp_msgs::MoveItPlugin >
template<>
struct DataType< ::pp_msgs::MoveItPluginResponse>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::MoveItPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MoveItPluginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PP_MSGS_MESSAGE_MOVEITPLUGIN_H
