// Generated by gencpp from file pp_msgs/PathPlanningPlugin.msg
// DO NOT EDIT!


#ifndef PP_MSGS_MESSAGE_PATHPLANNINGPLUGIN_H
#define PP_MSGS_MESSAGE_PATHPLANNINGPLUGIN_H

#include <ros/service_traits.h>


#include <pp_msgs/PathPlanningPluginRequest.h>
#include <pp_msgs/PathPlanningPluginResponse.h>


namespace pp_msgs
{

struct PathPlanningPlugin
{

typedef PathPlanningPluginRequest Request;
typedef PathPlanningPluginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlanningPlugin
} // namespace pp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pp_msgs::PathPlanningPlugin > {
  static const char* value()
  {
    return "9d98043111b72f254c7b31083eb22c8c";
  }

  static const char* value(const ::pp_msgs::PathPlanningPlugin&) { return value(); }
};

template<>
struct DataType< ::pp_msgs::PathPlanningPlugin > {
  static const char* value()
  {
    return "pp_msgs/PathPlanningPlugin";
  }

  static const char* value(const ::pp_msgs::PathPlanningPlugin&) { return value(); }
};


// service_traits::MD5Sum< ::pp_msgs::PathPlanningPluginRequest> should match
// service_traits::MD5Sum< ::pp_msgs::PathPlanningPlugin >
template<>
struct MD5Sum< ::pp_msgs::PathPlanningPluginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::PathPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::PathPlanningPluginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::PathPlanningPluginRequest> should match
// service_traits::DataType< ::pp_msgs::PathPlanningPlugin >
template<>
struct DataType< ::pp_msgs::PathPlanningPluginRequest>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::PathPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::PathPlanningPluginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pp_msgs::PathPlanningPluginResponse> should match
// service_traits::MD5Sum< ::pp_msgs::PathPlanningPlugin >
template<>
struct MD5Sum< ::pp_msgs::PathPlanningPluginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::PathPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::PathPlanningPluginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::PathPlanningPluginResponse> should match
// service_traits::DataType< ::pp_msgs::PathPlanningPlugin >
template<>
struct DataType< ::pp_msgs::PathPlanningPluginResponse>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::PathPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::PathPlanningPluginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PP_MSGS_MESSAGE_PATHPLANNINGPLUGIN_H
